name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello It is working"
      - name: exiting now
        run: echo "test ran completed"
      - name: update ubuntu
        run: sudo apt-get update -y

